In [36]:
import pandas

dataset = pandas.read_csv("Dataset/Clean_UK_Accident.csv")

In [37]:
dataset["Accident_Severity"].value_counts()

Accident_Severity
3    1263824
2     199364
1      18214
Name: count, dtype: int64

In [38]:
pandas.set_option('display.max_rows', 10)
dataset.head(100)

    Unnamed: 0 Accident_Index  Location_Easting_OSGR  Location_Northing_OSGR  \
0            0  200501BS00001               525680.0                178240.0
1            1  200501BS00002               524170.0                181650.0
2            2  200501BS00003               524520.0                182240.0
3            3  200501BS00004               526900.0                177530.0
4            4  200501BS00005               528060.0                179040.0
..         ...            ...                    ...                     ...
95          95  200501BS70077               524430.0                181060.0
96          96  200501BS70078               524050.0                179700.0
97          97  200501BS70079               526090.0                177600.0
98          98  200501BS70080               525370.0                180290.0
99          99  200501BS70082               525350.0                178030.0

    Longitude   Latitude  Police_Force  Accident_Severity  Number_of_Vehicles  \
0   -0.191170  51.489096             1                  2                   1
1   -0.211708  51.520075             1                  3                   1
2   -0.206458  51.525301             1                  3                   2
3   -0.173862  51.482442             1                  3                   1
4   -0.156618  51.495752             1                  3                   1
..        ...        ...           ...                ...                 ...
95  -0.208171  51.514716             1                  3                   2
96  -0.214123  51.502577             1                  3                   2
97  -0.185496  51.483253             1                  3                   3
98  -0.194905  51.507588             1                  3                   3
99  -0.195995  51.487281             1                  3                   1

    Number_of_Casualties  ...      Pedestrian_Crossing-Physical_Facilities  \
0                      1  ...                               Zebra crossing
1                      1  ...  Pedestrian phase at traffic signal junction
2                      1  ...        No physical crossing within 50 meters
3                      1  ...        No physical crossing within 50 meters
4                      1  ...        No physical crossing within 50 meters
..                   ...  ...                                          ...
95                     1  ...        No physical crossing within 50 meters
96                     1  ...  Pedestrian phase at traffic signal junction
97                     1  ...  Pedestrian phase at traffic signal junction
98                     2  ...                               Zebra crossing
99                     1  ...        No physical crossing within 50 meters

                           Light_Conditions          Weather_Conditions  \
0            Daylight: Street light present  Raining without high winds
1   Darkness: Street lights present and lit     Fine without high winds
2   Darkness: Street lights present and lit     Fine without high winds
3            Daylight: Street light present     Fine without high winds
4         Darkness: Street lighting unknown     Fine without high winds
..                                      ...                         ...
95           Daylight: Street light present     Fine without high winds
96           Daylight: Street light present     Fine without high winds
97           Daylight: Street light present     Fine without high winds
98           Daylight: Street light present     Fine without high winds
99           Daylight: Street light present     Fine without high winds

    Road_Surface_Conditions            Special_Conditions_at_Site  \
0                  Wet/Damp                                   NaN
1                       Dry                                   NaN
2                       Dry                                   NaN
3                       Dry                                   NaN
4                  Wet/Damp                                   NaN
..                      ...                                   ...
95                      Dry                                   NaN
96                      Dry                                   NaN
97                      Dry  Auto traffic signal partly defective
98                      Dry                                   NaN
99                 Wet/Damp                                   NaN

    Carriageway_Hazards  Urban_or_Rural_Area  \
0                   NaN                    1
1                   NaN                    1
2                   NaN                    1
3                   NaN                    1
4                   NaN                    1
..                  ...                  ...
95                  NaN                    1
96                  NaN                    1
97                  NaN                    1
98                  NaN                    1
99                  NaN                    1

   Did_Police_Officer_Attend_Scene_of_Accident  LSOA_of_Accident_Location  \
0                                          Yes                  E01002849
1                                          Yes                  E01002909
2                                          Yes                  E01002857
3                                          Yes                  E01002840
4                                          Yes                  E01002863
..                                         ...                        ...
95                                         Yes                  E01002874
96                                         Yes                  E01002869
97                                         Yes                  E01002912
98                                         Yes                  E01002827
99                                         Yes                  E01001883

    Year
0   2005
1   2005
2   2005
3   2005
4   2005
..   ...
95  2005
96  2005
97  2005
98  2005
99  2005

[100 rows x 33 columns]

In [12]:
values_list = set(dataset['Light_Conditions'].tolist())
values_list

{'Darkeness: No street lighting',
 'Darkness: Street lighting unknown',
 'Darkness: Street lights present and lit',
 'Darkness: Street lights present but unlit',
 'Daylight: Street light present'}

In [14]:
pandas.set_option('display.max_columns', 35)
dataset.head()

c:\Cours\I1\S5\IML\PRJ\Intro_AI_MT-MG\Dependency\File_converter.py:15: DtypeWarning: Columns (0: Location_Easting_OSGR, 1: Longitude) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pandas.read_csv("./Dataset/UK_Accident.csv",na_filter=False)

         Unnamed: 0 Accident_Index  Longitude   Latitude  Police_Force  \
274504       274504  200620F142203  -1.920926  52.545956            20
1261210      221757       2.01E+12   -0.50752  54.368717            12
139894       139894       2.01E+12  -1.661835  50.758089            44
972078       402067  201134TM80101  -0.940127  52.208313            34
1115255       75802       2.01E+12  -1.382735  54.976974            10
...             ...            ...        ...        ...           ...
380147       380147       2.01E+12  -2.964908  55.626501            95
761548       191537  201004DF10083   -2.75843  53.812573             4
1377592      338139  201401VW40019  -0.199078  51.434632             1
549914       549914  2007600DE4003  -3.467324  53.290724            60
500720       500720  20074100T3079  -0.448591  51.683600            41

         Accident_Severity  Number_of_Vehicles  Number_of_Casualties  \
274504                   1                   1                     1
1261210                  1                   2                     1
139894                   1                   1                     1
972078                   1                   1                     3
1115255                  1                   3                     1
...                    ...                 ...                   ...
380147                   3                   1                     2
761548                   3                   2                     1
1377592                  3                   2                     1
549914                   3                   3                     1
500720                   3                   2                     2

               Date  Day_of_Week  ... Pedestrian_Crossing-Human_Control  \
274504   24/06/2006            7  ...             None within 50 metres
1261210  12/05/2013            1  ...             None within 50 metres
139894   14/09/2005            4  ...             None within 50 metres
972078   13/08/2011            7  ...             None within 50 metres
1115255  11/09/2012            3  ...             None within 50 metres
...             ...          ...  ...                               ...
380147   31/08/2006            5  ...             None within 50 metres
761548   13/10/2010            4  ...             None within 50 metres
1377592  07/01/2014            3  ...             None within 50 metres
549914   09/01/2007            3  ...             None within 50 metres
500720   25/05/2007            6  ...             None within 50 metres

         Pedestrian_Crossing-Physical_Facilities Light_Conditions  \
274504     No physical crossing within 50 meters                0
1261210    No physical crossing within 50 meters                0
139894     No physical crossing within 50 meters                0
972078     No physical crossing within 50 meters                1
1115255    No physical crossing within 50 meters                0
...                                          ...              ...
380147     No physical crossing within 50 meters                0
761548     No physical crossing within 50 meters                0
1377592    No physical crossing within 50 meters                1
549914                            Zebra crossing                1
500720     No physical crossing within 50 meters                0

              Weather_Conditions  Road_Surface_Conditions  \
274504   Fine without high winds                      Dry
1261210  Fine without high winds                      Dry
139894   Fine without high winds                      Dry
972078   Fine without high winds                      Dry
1115255  Fine without high winds                      Dry
...                          ...                      ...
380147   Fine without high winds                 Wet/Damp
761548   Fine without high winds                      Dry
1377592  Fine without high winds                      Dry
549914   Fine without high winds                 Wet/Damp
500720   Fine without high winds                      Dry

        Special_Conditions_at_Site  Carriageway_Hazards Urban_or_Rural_Area  \
274504                        None                 None                   1
1261210                       None                 None                   2
139894                        None                 None                   1
972078                        None                 None                   2
1115255                       None                 None                   1
...                            ...                  ...                 ...
380147                        None                 None                   2
761548                        None                 None                   2
1377592                       None                 None                   1
549914                        None                 None                   2
500720                        None                 None                   2

         Did_Police_Officer_Attend_Scene_of_Accident  Year
274504                                           Yes  2006
1261210                                          Yes  2013
139894                                           Yes  2005
972078                                           Yes  2011
1115255                                          Yes  2012
...                                              ...   ...
380147                                           Yes  2006
761548                                           Yes  2010
1377592                                           No  2014
549914                                           Yes  2007
500720                                           Yes  2007

[30000 rows x 30 columns]

,Unnamed: 0,Accident_Index,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,...,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,Year
274504,274504,200620F142203,-1.920926,52.545956,20,1,1,1,24/06/2006,7,...,None within 50 metres,No physical crossing within 50 meters,0,Fine without high winds,Dry,None,None,1,Yes,2006
1261210,221757,2.01E+12,-0.50752,54.368717,12,1,2,1,12/05/2013,1,...,None within 50 metres,No physical crossing within 50 meters,0,Fine without high winds,Dry,None,None,2,Yes,2013
139894,139894,2.01E+12,-1.661835,50.758089,44,1,1,1,14/09/2005,4,...,None within 50 metres,No physical crossing within 50 meters,0,Fine without high winds,Dry,None,None,1,Yes,2005
972078,402067,201134TM80101,-0.940127,52.208313,34,1,1,3,13/08/2011,7,...,None within 50 metres,No physical crossing within 50 meters,1,Fine without high winds,Dry,None,None,2,Yes,2011
1115255,75802,2.01E+12,-1.382735,54.976974,10,1,3,1,11/09/2012,3,...,None within 50 metres,No physical crossing within 50 meters,0,Fine without high winds,Dry,None,None,1,Yes,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380147,380147,2.01E+12,-2.964908,55.626501,95,3,1,2,31/08/2006,5,...,None within 50 metres,No physical crossing within 50 meters,0,Fine without high winds,Wet/Damp,None,None,2,Yes,2006
761548,191537,201004DF10083,-2.75843,53.812573,4,3,2,1,13/10/2010,4,...,None within 50 metres,No physical crossing within 50 meters,0,Fine without high winds,Dry,None,None,2,Yes,2010
1377592,338139,201401VW40019,-0.199078,51.434632,1,3,2,1,07/01/2014,3,...,None within 50 metres,No physical crossing within 50 meters,1,Fine without high winds,Dry,None,None,1,No,2014
549914,549914,2007600DE4003,-3.467324,53.290724,60,3,3,1,09/01/2007,3,...,None within 50 metres,Zebra crossing,1,Fine without high winds,Wet/Damp,None,None,2,Yes,2007
500720,500720,20074100T3079,-0.448591,51.683600,41,3,2,2,25/05/2007,6,...,None within 50 metres,No physical crossing within 50 meters,0,Fine without high winds,Dry,None,None,2,Yes,2007

In [39]:
test = dataset.columns.to_list()
delete = ["Unnamed: 0", "Unnamed: 0.1", "Accident_Index","Location_Easting_OSGR","Location_Northing_OSGR","Longitude","Latitude","LSOA_of_Accident_Location"]
for i in delete:
    if i in test:
        test.remove(i)
for val in test:
    print(dataset[val].value_counts())
    print("\n")

Accident_Severity
3    1263824
2     199364
1      18214
Name: count, dtype: int64


Number_of_Vehicles
2    886176
1    454101
3    116979
4     24146
Name: count, dtype: int64


Number_of_Casualties
1    1150454
2     239131
3      67522
4      24295
Name: count, dtype: int64


Day_of_Week
6    243380
5    223523
4    223487
3    221280
2    210786
7    197538
1    161408
Name: count, dtype: int64


Time
17:00    14633
17:30    13907
16:00    13286
18:00    13068
15:30    13025
         ...
04:13       50
04:01       47
04:34       45
04:41       44
04:46       40
Name: count, Length: 1439, dtype: int64


1st_Road_Class
3    672769
6    427851
4    189144
5    133237
1     54506
2      3895
Name: count, dtype: int64


Road_Type
Single carriageway    1112596
Dual carriageway       214537
Roundabout              99894
One way street          30751
Slip road               15358
Unknown                  8266
Name: count, dtype: int64


Speed_limit
30    959321
60    233126
40    120320
70    104073
50     47510
20     17052
Name: count, dtype: int64


Junction_Control
Giveway or uncontrolled     725985
Automatic traffic signal    153747
Stop Sign                     9035
Authorised person             2456
Name: count, dtype: int64


2nd_Road_Class
-1    602663
 6    591808
 3    148162
 5     69481
 4     58251
 1      9904
 2      1133
Name: count, dtype: int64


Pedestrian_Crossing-Physical_Facilities
No physical crossing within 50 meters          1232139
Pedestrian phase at traffic signal junction      99175
non-junction pedestrian crossing                 78522
Zebra crossing                                   39905
Central refuge                                   27384
Footbridge or subway                              4244
Name: count, dtype: int64


Light_Conditions
Daylight: Street light present               1086703
Darkness: Street lights present and lit       291589
Darkeness: No street lighting                  80416
Darkness: Street lighting unknown              15905
Darkness: Street lights present but unlit       6789
Name: count, dtype: int64


Weather_Conditions
Fine without high winds       1185861
Raining without high winds     174726
Other                           33047
Unknown                         28201
Raining with high winds         20460
Fine with high winds            18079
Snowing without high winds      11133
Fog or mist                      7995
Snowing with high winds          1900
Name: count, dtype: int64


Road_Surface_Conditions
Dry                          1019844
Wet/Damp                      416269
Frost/Ice                      30915
Snow                           10341
Flood (Over 3cm of water)       2091
Normal                          1942
Name: count, dtype: int64


Urban_or_Rural_Area
1    961947
2    519455
Name: count, dtype: int64


Did_Police_Officer_Attend_Scene_of_Accident
Yes    1197086
No      284316
Name: count, dtype: int64


Year
2005    195423
2006    186164
2007    179238
2012    177030
2009    161048
2010    152217
2011    149270
2014    144243
2013    136769
Name: count, dtype: int64

In [40]:
dataset.groupby("Accident_Severity")['Number_of_Casualties'].mean()

Accident_Severity
1    1.623861
2    1.354688
3    1.288794
Name: Number_of_Casualties, dtype: float64