In [1]:
import pandas

#reading uncleaned dataset

dataset = pandas.read_csv("Dataset/UK_Accident.csv")

#understanding dataset

pandas.set_option('display.max_columns', 35)
dataset.head()

,Unnamed: 0,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,Time,Local_Authority_(District),Local_Authority_(Highway),1st_Road_Class,1st_Road_Number,Road_Type,Speed_limit,Junction_Control,2nd_Road_Class,2nd_Road_Number,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Year
0,0,200501BS00001,525680.0,178240.0,-0.191170,51.489096,1,2,1,1,04/01/2005,3,17:42,12,E09000020,3,3218,Single carriageway,30,NaN,-1,0,None within 50 metres,Zebra crossing,Daylight: Street light present,Raining without high winds,Wet/Damp,NaN,NaN,1,Yes,E01002849,2005
1,1,200501BS00002,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,05/01/2005,4,17:36,12,E09000020,4,450,Dual carriageway,30,Automatic traffic signal,5,0,None within 50 metres,Pedestrian phase at traffic signal junction,Darkness: Street lights present and lit,Fine without high winds,Dry,NaN,NaN,1,Yes,E01002909,2005
2,2,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,5,00:15,12,E09000020,5,0,Single carriageway,30,NaN,-1,0,None within 50 metres,No physical crossing within 50 meters,Darkness: Street lights present and lit,Fine without high winds,Dry,NaN,NaN,1,Yes,E01002857,2005
3,3,200501BS00004,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,07/01/2005,6,10:35,12,E09000020,3,3220,Single carriageway,30,NaN,-1,0,None within 50 metres,No physical crossing within 50 meters,Daylight: Street light present,Fine without high winds,Dry,NaN,NaN,1,Yes,E01002840,2005
4,4,200501BS00005,528060.0,179040.0,-0.156618,51.495752,1,3,1,1,10/01/2005,2,21:13,12,E09000020,6,0,Single carriageway,30,NaN,-1,0,None within 50 metres,No physical crossing within 50 meters,Darkness: Street lighting unknown,Fine without high winds,Wet/Damp,NaN,NaN,1,Yes,E01002863,2005

In [2]:
#counting all class / value in most colunms

test = dataset.columns.to_list()
delete = ["Unnamed: 0", "Unnamed: 0.1", "Accident_Index","Location_Easting_OSGR","Location_Northing_OSGR","Longitude","Latitude","LSOA_of_Accident_Location"]
for i in delete:
    if i in test:
        test.remove(i)
for val in test:
    print(dataset[val].value_counts())
    print("\n")

Police_Force
1     227502
20     60547
6      58991
13     55675
43     54554
46     46069
44     45156
4      44781
50     42481
97     40839
42     40095
47     40054
45     37424
52     36936
10     36912
5      34042
14     33079
7      31265
21     30210
31     28667
41     26927
62     26494
22     25867
30     25791
33     24303
16     23803
35     23454
12     22661
32     21357
95     21262
55     18693
36     18468
37     17257
60     15285
23     15039
3      14474
11     14390
40     14235
54     14220
63     13615
34     13014
53     11428
92      9524
17      9422
61      8514
93      7201
91      5674
96      5242
94      4827
98      3400
48      3030
Name: count, dtype: int64


Accident_Severity
3    1280205
2     204504
1      19441
Name: count, dtype: int64


Number_of_Vehicles
2     894284
1     455663
3     120122
4      25498
5       5653
6       1748
7        611
8        293
9        132
10        63
11        26
12        15
13        12
14         7
18         4
16         4
15         3
20         2
19         2
17         1
22         1
28         1
32         1
29         1
34         1
67         1
21         1
Name: count, dtype: int64


Number_of_Casualties
1     1153856
2      241290
3       68858
4       25045
5        9216
6        3486
7        1161
8         511
9         246
10        134
11         88
12         47
13         42
14         27
15         16
17         15
16         15
18         11
22         11
19          9
21          8
26          7
29          6
23          4
20          4
25          4
24          4
42          3
41          2
36          2
40          2
27          2
43          2
87          2
51          2
35          1
45          1
28          1
68          1
48          1
63          1
33          1
38          1
46          1
70          1
93          1
54          1
Name: count, dtype: int64


Date
21/10/2005    822
18/11/2005    787
29/09/2006    784
22/09/2006    780
07/12/2005    775
             ...
25/12/2007    157
02/01/2011    146
25/12/2011    142
10/01/2010    130
25/12/2014    128
Name: count, Length: 3286, dtype: int64


Day_of_Week
6    247137
5    226411
4    226359
3    224110
2    213748
7    201413
1    164972
Name: count, dtype: int64


Time
17:00    14765
17:30    14036
16:00    13434
18:00    13194
15:30    13170
         ...
04:54       50
04:01       49
04:34       48
04:41       45
04:46       43
Name: count, Length: 1439, dtype: int64


Local_Authority_(District)
300    27675
204    19984
102    14999
91     14068
1      13644
       ...
941      318
936      312
166      267
141      251
933      237
Name: count, Length: 416, dtype: int64


Local_Authority_(Highway)
E10000016    40391
E10000030    37424
E10000017    35630
E10000012    31993
E10000014    29852
             ...
EHEATHROW      362
S12000013      318
S12000027      312
S12000023      237
E06000053       19
Name: count, Length: 207, dtype: int64


1st_Road_Class
3    684509
6    431908
4    191381
5    134513
1     57779
2      4060
Name: count, dtype: int64


1st_Road_Number
0       406849
1        19070
6        16648
4        14179
25        9794
         ...
5673         1
5542         1
2655         1
9055         1
8086         1
Name: count, Length: 6854, dtype: int64


Road_Type
Single carriageway    1126951
Dual carriageway       221741
Roundabout             100463
One way street          30981
Slip road               15668
Unknown                  8346
Name: count, dtype: int64


Speed_limit
30    968284
60    238234
40    122393
70    109268
50     48790
20     17157
10        14
15        10
Name: count, dtype: int64


Junction_Control
Giveway or uncontrolled     733940
Automatic traffic signal    155717
Stop Sign                     9179
Authorised person             2479
Name: count, dtype: int64


2nd_Road_Class
-1    615474
 6    598326
 3    149758
 5     70366
 4     58918
 1     10146
 2      1162
Name: count, dtype: int64


2nd_Road_Number
 0       1165105
-1         14451
 1          3601
 6          2984
 4          2892
          ...
 8044          1
 1545          1
 4573          1
 9057          1
 9136          1
Name: count, Length: 7235, dtype: int64


Pedestrian_Crossing-Human_Control
None within 50 metres                 1495269
Control by other authorised person       5220
Control by school crossing patrol        3644
Name: count, dtype: int64


Pedestrian_Crossing-Physical_Facilities
No physical crossing within 50 meters          1252571
Pedestrian phase at traffic signal junction     100248
non-junction pedestrian crossing                 79231
Zebra crossing                                   40106
Central refuge                                   27660
Footbridge or subway                              4300
Name: count, dtype: int64


Light_Conditions
Daylight: Street light present               1102222
Darkness: Street lights present and lit       296340
Darkeness: No street lighting                  82559
Darkness: Street lighting unknown              16120
Darkness: Street lights present but unlit       6909
Name: count, dtype: int64


Weather_Conditions
Fine without high winds       1203943
Raining without high winds     177663
Other                           33503
Unknown                         28422
Raining with high winds         20813
Fine with high winds            18355
Snowing without high winds      11301
Fog or mist                      8190
Snowing with high winds          1960
Name: count, dtype: int64


Road_Surface_Conditions
Dry                          1034670
Wet/Damp                      423477
Frost/Ice                      31405
Snow                           10497
Flood (Over 3cm of water)       2143
Normal                          1958
Name: count, dtype: int64


Special_Conditions_at_Site
Roadworks                                          17223
Ol or diesel                                        5243
Mud                                                 4610
Road surface defective                              3664
Auto traffic singal out                             2788
Permanent sign or marking defective or obscured     2269
Auto traffic signal partly defective                 785
Name: count, dtype: int64


Carriageway_Hazards
Other object in carriageway                11762
Any animal (except a ridden horse)          8014
Pedestrian in carriageway (not injured)     3586
Involvement with previous accident          2282
Dislodged vehicle load in carriageway       1606
Name: count, dtype: int64


Urban_or_Rural_Area
1    972007
2    532011
3       132
Name: count, dtype: int64


Did_Police_Officer_Attend_Scene_of_Accident
Yes    1218877
No      285273
Name: count, dtype: int64


Year
2005    198735
2006    189161
2007    182115
2012    179715
2009    163554
2010    154414
2011    151474
2014    146322
2013    138660
Name: count, dtype: int64

In [10]:
#seeing variables relationships

for val in test:
    print(dataset.groupby(val)["Accident_Severity"].mean())
    print("\n")

Accident_Severity
1    1.0
2    2.0
3    3.0
Name: Accident_Severity, dtype: float64


Number_of_Vehicles
1     2.764859
2     2.873807
3     2.856338
4     2.836772
5     2.796391
6     2.744851
7     2.721768
8     2.675768
9     2.659091
10    2.587302
11    2.692308
12    2.666667
13    2.500000
14    2.428571
15    3.000000
16    2.500000
17    2.000000
18    2.750000
19    2.000000
20    3.000000
21    2.000000
22    2.000000
28    1.000000
29    2.000000
32    3.000000
34    1.000000
67    2.000000
Name: Accident_Severity, dtype: float64


Number_of_Casualties
1     2.850423
2     2.827494
3     2.772009
4     2.704252
5     2.638997
6     2.564257
7     2.514212
8     2.516634
9     2.524390
10    2.537313
11    2.409091
12    2.489362
13    2.357143
14    2.407407
15    2.187500
16    2.133333
17    2.200000
18    2.363636
19    2.777778
20    2.750000
21    2.125000
22    2.454545
23    2.750000
24    2.000000
25    3.000000
26    2.285714
27    1.500000
28    3.000000
29    2.000000
33    3.000000
35    2.000000
36    2.000000
38    1.000000
40    2.000000
41    2.500000
42    1.333333
43    2.000000
45    1.000000
46    2.000000
48    1.000000
51    1.000000
54    2.000000
63    3.000000
68    1.000000
70    2.000000
87    2.000000
93    2.000000
Name: Accident_Severity, dtype: float64


Day_of_Week
1    2.801294
2    2.847007
3    2.849195
4    2.851201
5    2.846121
6    2.843710
7    2.816501
Name: Accident_Severity, dtype: float64


Time
00:01    2.771137
00:02    2.686901
00:03    2.785425
00:04    2.746835
00:05    2.783094
           ...
23:55    2.758325
23:56    2.696133
23:57    2.710526
23:58    2.782258
23:59    2.782209
Name: Accident_Severity, Length: 1439, dtype: float64


1st_Road_Class
1    2.865384
2    2.843596
3    2.831634
4    2.823823
5    2.838216
6    2.851251
Name: Accident_Severity, dtype: float64


Road_Type
Dual carriageway      2.845545
One way street        2.861367
Roundabout            2.905896
Single carriageway    2.828964
Slip road             2.895456
Unknown               2.880062
Name: Accident_Severity, dtype: float64


Speed_limit
10    2.571429
15    3.000000
20    2.845428
30    2.861842
40    2.835530
50    2.809900
60    2.750602
70    2.834059
Name: Accident_Severity, dtype: float64


Junction_Control
Authorised person           2.887858
Automatic traffic signal    2.881773
Giveway or uncontrolled     2.858864
Stop Sign                   2.879072
Name: Accident_Severity, dtype: float64


2nd_Road_Class
-1    2.801667
 1    2.897299
 2    2.906196
 3    2.893014
 4    2.866764
 5    2.858369
 6    2.855717
Name: Accident_Severity, dtype: float64


Pedestrian_Crossing-Physical_Facilities
Central refuge                                 2.805640
Footbridge or subway                           2.841860
No physical crossing within 50 meters          2.835924
Pedestrian phase at traffic signal junction    2.868197
Zebra crossing                                 2.861367
non-junction pedestrian crossing               2.835519
Name: Accident_Severity, dtype: float64


Light_Conditions
Darkeness: No street lighting                2.719510
Darkness: Street lighting unknown            2.848449
Darkness: Street lights present and lit      2.823294
Darkness: Street lights present but unlit    2.815892
Daylight: Street light present               2.851074
Name: Accident_Severity, dtype: float64


Weather_Conditions
Fine with high winds          2.816562
Fine without high winds       2.832991
Fog or mist                   2.816239
Other                         2.872698
Raining with high winds       2.840052
Raining without high winds    2.858434
Snowing with high winds       2.872449
Snowing without high winds    2.888594
Unknown                       2.887728
Name: Accident_Severity, dtype: float64


Road_Surface_Conditions
Dry                          2.835924
Flood (Over 3cm of water)    2.827345
Frost/Ice                    2.864034
Normal                       2.885087
Snow                         2.887492
Wet/Damp                     2.840426
Name: Accident_Severity, dtype: float64


Urban_or_Rural_Area
1    2.862637
2    2.793517
3    2.871212
Name: Accident_Severity, dtype: float64


Did_Police_Officer_Attend_Scene_of_Accident
No     2.934635
Yes    2.815618
Name: Accident_Severity, dtype: float64


Year
2005    2.844743
2006    2.837186
2007    2.836642
2009    2.840352
2010    2.845208
2011    2.837728
2012    2.829964
2013    2.835281
2014    2.836033
Name: Accident_Severity, dtype: float64

In [11]:
#same as before but with balanced accident_severity class

dataset = dataset.groupby('Accident_Severity').sample(n=10000, random_state=1)

for val in test:
    print(dataset.groupby(val)["Accident_Severity"].mean())
    print("\n")

Accident_Severity
1    1.0
2    2.0
3    3.0
Name: Accident_Severity, dtype: float64


Number_of_Vehicles
1     1.855490
2     2.144263
3     1.928370
4     1.797508
5     1.777108
6     1.469697
7     1.793103
8     1.200000
9     1.466667
10    1.333333
11    1.000000
12    1.500000
13    1.000000
14    1.000000
67    2.000000
Name: Accident_Severity, dtype: float64


Number_of_Casualties
1     2.103337
2     1.862221
3     1.717523
4     1.557522
5     1.552174
6     1.384615
7     1.347826
8     1.192308
9     1.560000
10    1.333333
11    1.333333
12    2.000000
13    1.250000
14    1.000000
15    1.500000
17    2.000000
18    1.000000
21    1.000000
29    2.000000
42    1.000000
43    1.000000
45    1.000000
48    1.000000
51    1.000000
68    1.000000
70    2.000000
Name: Accident_Severity, dtype: float64


Day_of_Week
1    1.863509
2    2.035750
3    2.069734
4    2.056482
5    2.051885
6    2.020245
7    1.899452
Name: Accident_Severity, dtype: float64


Time
00:01    1.947368
00:02    1.600000
00:03    2.111111
00:04    2.000000
00:05    2.000000
           ...
23:55    1.800000
23:56    1.888889
23:57    1.750000
23:58    1.714286
23:59    1.909091
Name: Accident_Severity, Length: 1424, dtype: float64


1st_Road_Class
1    1.904282
2    1.721649
3    1.927552
4    1.960605
5    2.038636
6    2.170342
Name: Accident_Severity, dtype: float64


Road_Type
Dual carriageway      1.899586
One way street        2.230476
Roundabout            2.418951
Single carriageway    1.989038
Slip road             2.217021
Unknown               2.206897
Name: Accident_Severity, dtype: float64


Speed_limit
10    1.000000
20    2.215753
30    2.201683
40    1.941513
50    1.820714
60    1.682760
70    1.796685
Name: Accident_Severity, dtype: float64


Junction_Control
Authorised person           2.205882
Automatic traffic signal    2.250414
Giveway or uncontrolled     2.147637
Stop Sign                   2.140741
Name: Accident_Severity, dtype: float64


2nd_Road_Class
-1    1.836876
 1    2.108844
 2    2.312500
 3    2.295097
 4    2.196970
 5    2.117842
 6    2.144219
Name: Accident_Severity, dtype: float64


Pedestrian_Crossing-Physical_Facilities
Central refuge                                 1.933007
Footbridge or subway                           1.795181
No physical crossing within 50 meters          1.976138
Pedestrian phase at traffic signal junction    2.207164
Zebra crossing                                 2.240181
non-junction pedestrian crossing               2.103922
Name: Accident_Severity, dtype: float64


Light_Conditions
Darkeness: No street lighting                1.572816
Darkness: Street lighting unknown            2.112957
Darkness: Street lights present and lit      1.962231
Darkness: Street lights present but unlit    1.801282
Daylight: Street light present               2.077015
Name: Accident_Severity, dtype: float64


Weather_Conditions
Fine with high winds          1.868481
Fine without high winds       1.987644
Fog or mist                   1.815789
Other                         2.114232
Raining with high winds       1.960880
Raining without high winds    2.074828
Snowing with high winds       2.241379
Snowing without high winds    2.239130
Unknown                       2.148148
Name: Accident_Severity, dtype: float64


Road_Surface_Conditions
Dry                          2.012117
Flood (Over 3cm of water)    1.914894
Frost/Ice                    2.038529
Normal                       2.176471
Snow                         2.269231
Wet/Damp                     1.963084
Name: Accident_Severity, dtype: float64


Urban_or_Rural_Area
1    2.186002
2    1.784486
3    2.000000
Name: Accident_Severity, dtype: float64


Did_Police_Officer_Attend_Scene_of_Accident
No     2.613274
Yes    1.928460
Name: Accident_Severity, dtype: float64


Year
2005    1.967340
2006    1.930507
2007    1.963884
2009    2.014307
2010    2.050236
2011    2.026617
2012    2.035847
2013    2.016184
2014    2.036538
Name: Accident_Severity, dtype: float64

In [ ]:
#cleaning adn reading cleaned data

import pandas
from Dependency.File_converter import cleaning

#cleaning data

cleaning()

#reading the cleaned data

dataset_cleaned = pandas.read_csv("Dataset/Clean_UK_Accident.csv")

pandas.set_option('display.max_columns', 35)
dataset_cleaned.head()

,Unnamed: 0.1,Unnamed: 0,Longitude,Latitude,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Day_of_Week,Time,1st_Road_Class,Road_Type,Speed_limit,Junction_Control,2nd_Road_Class,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,Year
0,0,0,-0.191170,51.489096,2,1,1,3,17:42,3,0,30,0,-1,3.0,0,1,1,1,1,2005
1,1,1,-0.211708,51.520075,3,1,1,4,17:36,4,1,30,2,5,1.0,1,0,0,1,1,2005
2,2,2,-0.206458,51.525301,3,2,1,5,00:15,5,0,30,0,-1,0.0,1,0,0,1,1,2005
3,3,3,-0.173862,51.482442,3,1,1,6,10:35,3,0,30,0,-1,0.0,0,0,0,1,1,2005
4,4,4,-0.156618,51.495752,3,1,1,2,21:13,6,0,30,0,-1,0.0,2,0,1,1,1,2005

In [5]:
#counting all class in most colunms

test = dataset_cleaned.columns.to_list()
delete = ["Unnamed: 0", "Unnamed: 0.1", "Accident_Index","Location_Easting_OSGR","Location_Northing_OSGR","Longitude","Latitude","LSOA_of_Accident_Location"]
for i in delete:
    if i in test:
        test.remove(i)
for val in test:
    print(dataset_cleaned[val].value_counts())
    print("\n")

Accident_Severity
3    1263824
2     199364
1      18214
Name: count, dtype: int64


Number_of_Vehicles
2    886176
1    454101
3    116979
4     24146
Name: count, dtype: int64


Number_of_Casualties
1    1150454
2     239131
3      67522
4      24295
Name: count, dtype: int64


Day_of_Week
6    243380
5    223523
4    223487
3    221280
2    210786
7    197538
1    161408
Name: count, dtype: int64


Time
17:00    14633
17:30    13907
16:00    13286
18:00    13068
15:30    13025
         ...
04:13       50
04:01       47
04:34       45
04:41       44
04:46       40
Name: count, Length: 1439, dtype: int64


1st_Road_Class
3    672769
6    427851
4    189144
5    133237
1     54506
2      3895
Name: count, dtype: int64


Road_Type
0    1112596
1     214537
2      99894
3      30751
4      15358
5       8266
Name: count, dtype: int64


Speed_limit
30    959321
60    233126
40    120320
70    104073
50     47510
20     17052
Name: count, dtype: int64


Junction_Control
1    725985
0    590179
2    153747
3      9035
4      2456
Name: count, dtype: int64


2nd_Road_Class
-1    602663
 6    591808
 3    148162
 5     69481
 4     58251
 1      9904
 2      1133
Name: count, dtype: int64


Pedestrian_Crossing-Physical_Facilities
0.0    1232139
1.0      99175
2.0      78522
3.0      39905
4.0      27384
5.0       4244
Name: count, dtype: int64


Light_Conditions
0    1086703
1     291589
4      80416
2      15905
3       6789
Name: count, dtype: int64


Weather_Conditions
0    1185861
1     174726
2      33047
3      28201
4      20460
5      18079
6      11133
7       7995
8       1900
Name: count, dtype: int64


Road_Surface_Conditions
0    1019844
1     416269
2      30915
3      10341
4       2091
5       1942
Name: count, dtype: int64


Urban_or_Rural_Area
1    961947
2    519455
Name: count, dtype: int64


Did_Police_Officer_Attend_Scene_of_Accident
1    1197086
0     284316
Name: count, dtype: int64


Year
2005    195423
2006    186164
2007    179238
2012    177030
2009    161048
2010    152217
2011    149270
2014    144243
2013    136769
Name: count, dtype: int64

In [6]:
#seeing variables relationships using covariance

print(dataset_cleaned.cov())

ValueError: could not convert string to float: '17:42'